-- =============================================================================
-- BÀI TẬP LỚN CƠ SỞ DỮ LIỆU
-- ĐỀ TÀI: HỆ THỐNG QUẢN LÝ HÃNG VẬN TẢI HÀNH KHÁCH ĐƯỜNG DÀI
-- FILE: 01_schema.sql - KHỞI TẠO CẤU TRÚC CƠ SỞ DỮ LIỆU (DDL)
-- =============================================================================

CREATE DATABASE IF NOT EXISTS QuanLyVanTai 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE QuanLyVanTai;

-- 1. BẢNG XE (Phương tiện khách)
DROP TABLE IF EXISTS LICH_SU_BAO_DUONG;
DROP TABLE IF EXISTS CHUYEN_XE;
DROP TABLE IF EXISTS TUYEN_XE;
DROP TABLE IF EXISTS TAI_XE;
DROP TABLE IF EXISTS XE;

CREATE TABLE XE (
    BienSo VARCHAR(20) NOT NULL,
    MauXe VARCHAR(50) NOT NULL,
    HangSanXuat VARCHAR(100) NOT NULL,
    DoiXe INT NOT NULL,
    Model VARCHAR(100) NOT NULL,
    SoGhe INT NOT NULL,
    SoNamSuDung INT NOT NULL DEFAULT 0,
    NgayBaoDuongCuoi DATE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_XE PRIMARY KEY (BienSo),
    CONSTRAINT CHK_XE_SoGhe CHECK (SoGhe >= 16),
    CONSTRAINT CHK_XE_SoNamSuDung CHECK (SoNamSuDung >= 0),
    CONSTRAINT CHK_XE_DoiXe CHECK (DoiXe >= 1990)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. BẢNG TAI_XE (Nhân sự lái xe & phụ xe)
CREATE TABLE TAI_XE (
    MaTaiXe INT NOT NULL AUTO_INCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    CCCD VARCHAR(20) NOT NULL,
    MaSoBangLai VARCHAR(30) NOT NULL,
    LoaiBangLai VARCHAR(10) NOT NULL,
    DiaChi VARCHAR(255) NULL,
    NgaySinh DATE NOT NULL,
    ThamNien INT NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_TAI_XE PRIMARY KEY (MaTaiXe),
    CONSTRAINT UQ_TAI_XE_CCCD UNIQUE (CCCD),
    CONSTRAINT UQ_TAI_XE_BangLai UNIQUE (MaSoBangLai),
    CONSTRAINT CHK_TAI_XE_ThamNien CHECK (ThamNien >= 0),
    CONSTRAINT CHK_TAI_XE_LoaiBangLai CHECK (LoaiBangLai IN ('D', 'E', 'FC', 'FD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. BẢNG TUYEN_XE (Lộ trình tuyến đường)
CREATE TABLE TUYEN_XE (
    MaTuyen INT NOT NULL AUTO_INCREMENT,
    DiemDau VARCHAR(100) NOT NULL,
    DiemCuoi VARCHAR(100) NOT NULL,
    DoDaiKm DECIMAL(8, 2) NOT NULL,
    DoPhucTap INT NOT NULL DEFAULT 1,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_TUYEN_XE PRIMARY KEY (MaTuyen),
    CONSTRAINT CHK_TUYEN_XE_DoDai CHECK (DoDaiKm > 0),
    CONSTRAINT CHK_TUYEN_XE_DoPhucTap CHECK (DoPhucTap IN (1, 2, 3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. BẢNG CHUYEN_XE (Điều phối chuyến xe)
CREATE TABLE CHUYEN_XE (
    MaChuyen INT NOT NULL AUTO_INCREMENT,
    MaTuyen INT NOT NULL,
    BienSoXe VARCHAR(20) NOT NULL,
    MaLaiXe INT NOT NULL,
    MaPhuXe INT NOT NULL,
    ThoiGianKhoiHanh DATETIME NOT NULL,
    ThoiGianKetThuc DATETIME NOT NULL,
    SoKhach INT NOT NULL DEFAULT 0,
    GiaVe DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    TrangThai VARCHAR(50) NOT NULL DEFAULT 'DaLenLich',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_CHUYEN_XE PRIMARY KEY (MaChuyen),
    CONSTRAINT FK_CHUYEN_XE_Tuyen FOREIGN KEY (MaTuyen) REFERENCES TUYEN_XE(MaTuyen) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_CHUYEN_XE_Xe FOREIGN KEY (BienSoXe) REFERENCES XE(BienSo) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_CHUYEN_XE_LaiXe FOREIGN KEY (MaLaiXe) REFERENCES TAI_XE(MaTaiXe) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_CHUYEN_XE_PhuXe FOREIGN KEY (MaPhuXe) REFERENCES TAI_XE(MaTaiXe) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT CHK_CHUYEN_XE_SoKhach CHECK (SoKhach >= 0),
    CONSTRAINT CHK_CHUYEN_XE_GiaVe CHECK (GiaVe >= 0),
    CONSTRAINT CHK_CHUYEN_XE_ThoiGian CHECK (ThoiGianKetThuc > ThoiGianKhoiHanh),
    CONSTRAINT CHK_CHUYEN_XE_TrangThai CHECK (TrangThai IN ('DaLenLich', 'DangChay', 'HoanThanh', 'Huy'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. BẢNG LICH_SU_BAO_DUONG (Nhật ký bảo dưỡng phương tiện)
CREATE TABLE LICH_SU_BAO_DUONG (
    MaBaoDuong INT NOT NULL AUTO_INCREMENT,
    BienSoXe VARCHAR(20) NOT NULL,
    NgayBaoDuong DATE NOT NULL,
    ChiPhi DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    NoiDung TEXT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_LICH_SU_BAO_DUONG PRIMARY KEY (MaBaoDuong),
    CONSTRAINT FK_BAO_DUONG_Xe FOREIGN KEY (BienSoXe) REFERENCES XE(BienSo) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT CHK_BAO_DUONG_ChiPhi CHECK (ChiPhi >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. TẠO CHỈ MỤC (INDEXES) ĐỂ TỐI ƯU HÓA TRUY VẤN
CREATE INDEX IDX_CHUYEN_XE_ThoiGian ON CHUYEN_XE(ThoiGianKhoiHanh, ThoiGianKetThuc);
CREATE INDEX IDX_CHUYEN_XE_BienSo ON CHUYEN_XE(BienSoXe);
CREATE INDEX IDX_CHUYEN_XE_LaiXe ON CHUYEN_XE(MaLaiXe);
CREATE INDEX IDX_CHUYEN_XE_PhuXe ON CHUYEN_XE(MaPhuXe);
CREATE INDEX IDX_CHUYEN_XE_Tuyen ON CHUYEN_XE(MaTuyen);
CREATE INDEX IDX_BAO_DUONG_Ngay ON LICH_SU_BAO_DUONG(BienSoXe, NgayBaoDuong);
